environment:
  global:
    RUST_VERSION: stable

  matrix:
    # Stable channel
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    # Beta channel
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: beta
    # Nightly channel
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly

install:
  - ps: >-
      $Env:PATH += ';C:\msys64\usr\bin'
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  - cargo build --verbose --features=cli
  - cargo test --features=cli

cache:
  - C:\Users\appveyor\.cargo\registry

# disable automatic builds
build: false
