schedules:
- cron: "12 12 12 * *"
  displayName: Monthly Build
  branches:
    include:
    - master

stages:
- template: azure/stages.yml@templates
  parameters:
    minrust: 1.34.0
    # Crashes for some reason. Note: does not run in PRs, so needs to be tested
    # in `master`.
    #codecov_token: $(CODECOV_TOKEN_SECRET)
- stage: committed
  displayName: Lint History
  dependsOn: []
  jobs:
  - job: "Committed"
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - checkout: self
    - template: v1/azdo-step.yml@gh-install
      parameters:
        git: crate-ci/committed
        target: 'x86_64-unknown-linux-gnu'
        to: $(Build.StagingDirectory)/tools
    - script: $(Build.StagingDirectory)/tools/committed HEAD~..HEAD^2 --no-merge-commit -vv
      displayName: Committed
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: crate-ci
    - repository: gh-install
      type: github
      name: crate-ci/gh-install
      endpoint: crate-ci
